project:
  type: website
  output-dir: docs

website:
  title: "Francisco Garre-Frutos"
  favicon: source/favicon-32.png # Provisional favicon
  description: "Francisco Garre-Frutos is a Ph.D student at University of Granada, researching about the influence of selection history on attentional capture (and coding and plotting things)."
  navbar:
    left:
      - text: About
        href: index.qmd
      - text: Portfolio
        href: posts.qmd

  page-footer:
    center: |
      <span class="faux-block">&#169; {{< var years >}}, {{< meta website.title >}}</span>


format:
  html:
    theme: styles.scss
    toc: true



